todo_app/project/models.py
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from db import Base
from models import TimestampMixin


class Project(Base, TimestampMixin):
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(ForeignKey("users.id"), nullable=False)
    name = Column(String(), nullable=False)

    user = relationship("User", back_populates="projects")
    tasks = relationship(
        "Task",
        cascade="all, delete-orphan",
        order_by="Task.completed, desc(Task.modified_at)",
    )
    collaborators = relationship("Collaborator", cascade="all, delete-orphan")

todo_app/project/blueprint.py
from flask import (
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    request,
    url_for,
)

from auth.utils import login_required
from db import db
from project.models import Project
from project.utils import get_project


bp = Blueprint("project", __name__, template_folder="templates")

bp.before_request(login_required())


@bp.get("/")
def index():
    return render_template("index.html", projects=g.user.projects)


@bp.get("/<int:project_id>")
def show_details(project_id):
    project = get_project(project_id)
    return render_template("details.html", project=project)


@bp.route("/create", methods=("GET", "POST"))
def create():
    if request.method == "POST":
        name = request.form["name"]

        error = None

        if not name:
            error = "Name is required."

        if not error:
            project_id = request.form.get("project_id")
            if project_id is not None:
                project = get_project(project_id, check_collaborator=False)
                project.name = name
            else:
                project = Project(name=name, user_id=g.user.id)
                db.session.add(project)

            db.session.commit()
            flash(
                f"Project {project.name} was {"updated" if project_id else "created"}."
            )
            return redirect(url_for("project.show_details", project_id=project.id))

        flash(error)

    project = None
    if request.method == "GET" and request.args.get("project_id") is not None:
        project = get_project(request.args.get("project_id"), check_collaborator=False)

    return render_template("create_project.html", project=project)


@bp.get("/<int:project_id>/delete")
def delete(project_id):
    project = get_project(project_id, check_collaborator=False)
    db.session.delete(project)
    db.session.commit()
    flash(f"Project {project.name} was deleted.")
    return redirect(url_for("project.index"))


@bp.get("/<int:project_id>/collaborators")
def show_collaborators(project_id):
    project = get_project(project_id)
    return render_template("show_collaborators.html", project=project)

todo_app/project/templates/create_project.html
{% extends "base.html" %}

{% if request.args.get("project_id") or project %}
    {% set title = "Update" %}
{% else %}
    {% set title = "Create" %}
{% endif %}


{% block content %}
    <h1 class="text-center">{% block title %}{{ title }}{% endblock %} project</h1>

    <div class="row justify-content-center">
        <form class="col-md-4" method="post">
            {% if title == "Update" %}
                <input name="project_id" type="hidden" value="{{ project.id }}">
            {% endif %}

            <div class="mb-3">
                <label for="name">Name</label>
                <input autocomplete="off" class="form-control" id="name" name="name" required type="text" value="{{ project.name }}">
            </div>
    
            <button class="btn btn-primary">{{ title }}</button>
        </form>
    </div>
{% endblock %}

todo_app/project/templates/details.html
{% extends 'base.html' %}

{% set ownership = g.user.id == project.user_id %}

{% block content %}
    <h1>{% block title %}{{ project.name }}{% endblock %}</h1>

    {% if ownership %}
    <a class="btn btn-primary" href="{{ url_for('project.create', project_id=project.id) }}">Edit project</a>
    
    <a class="btn btn-danger" href="{{ url_for('project.delete', project_id=project.id) }}">Delete project</a>

    <br>
        <a class="btn btn-primary mt-3" href="{{ url_for('collaborator.create', project_id=project.id) }}">Add collaborator</a>
    {% endif %}

    <a class="btn btn-primary {% if ownership %}mt-3{% endif %}" href="{{ url_for('project.show_collaborators', project_id=project.id) }}">Show collaborators</a>

    <h2 class="mt-5">Tasks</h2>

    <a class="btn btn-primary mb-3" href="{{ url_for('task.create', project_id=project.id) }}">Create task</a>

    {% if project.tasks %}
        <ul class="list-group">
            {% for task in project.tasks %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <a class="{% if task.completed %}text-success{% endif %}" href="{{ url_for('task.create', project_id=project.id, task_id=task.id) }}">{{ task.text }}</a>
                        {% if task.added_by_id != g.user.id %}
                            - Added by {{ task.added_by.name }}
                        {% endif %}
                    </div>
                    <a href="{{ url_for('task.completed', task_id=task.id) }}" class="btn btn-primary">
                        Mark as
                        {% if task.completed %}
                            uncompleted
                        {% else %}
                            completed
                        {% endif %}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No tasks in this project yet!</p>
    {% endif %}
{% endblock %}

todo_app/project/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %}Projects{% endblock %}</h1>

    <a class="btn btn-primary mb-3" href="{{ url_for('project.create') }}">Create a new project</a>

    {% if projects %}
        <ul class="list-group">
            {% for p in projects %}
                <li class="list-group-item"><a href="{{ url_for('project.show_details', project_id=p.id) }}">{{ p.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Create a project to get started!</p>
    {% endif %}
{% endblock %}

todo_app/project/templates/show_collaborators.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %}Collaborators{% endblock %}</h1>

    {% if project.collaborators %}
        <ul class="list-group">
            {% for collab in project.collaborators %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span>{{ collab.user.name }} - {{ collab.user.email }}</span>
                    {% if g.user.id == project.user_id %}
                        <a class="btn btn-danger" href="{{ url_for('collaborator.delete', collaborator_id=collab.id, project_id=project.id) }}">Delete</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        You have not invited anyone to this project.
        <br>
        <a class="btn btn-primary mt-3" href="{{ url_for('collaborator.create', project_id=project.id) }}">Add collaborator</a>
    {% endif %}
{% endblock %}