todo_app/auth.py
import functools
from flask import (
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from sqlalchemy import select
from werkzeug.security import generate_password_hash, check_password_hash
from sqlalchemy.exc import IntegrityError

from db import db
from models import Task, User, Project


bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/register", methods=("GET", "POST"))
def register():
    if g.user:
        return redirect(url_for("index"))

    elif request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        name = request.form["name"]

        error = None

        if not email or not password or not name:
            error = "Email, password, and name are required."

        if not error:
            try:
                password = generate_password_hash(password)
                user = User(email=email, password=password, name=name)
                project = Project(name="My first project")
                user.projects.append(project)
                task = Task(text="First task", completed=False)
                project.tasks.append(task)
                db.session.add(user)
                db.session.commit()
                flash("Registration successful! You can now log in.")

                return redirect(url_for("auth.login"))
            except IntegrityError as e:
                print(e)
                error = "Email is already registered."

        flash(error)

    return render_template("auth/register.html")


@bp.route("/login", methods=("GET", "POST"))
def login():
    if g.user:
        return redirect(url_for("index"))

    elif request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        error = None

        if not email or not password:
            error = "Email and password are required."

        if not error:
            stmt = select(User).where(User.email == email)
            user = db.session.scalar(stmt)
            if user and check_password_hash(user.password, password):
                session["user_id"] = user.id
                return redirect(url_for("index"))

            error = "Incorrect email or password."

        flash(error)

    return render_template("auth/login.html")


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        stmt = select(User).where(User.id == user_id)
        g.user = db.session.scalar(stmt)


@bp.get("/logout")
def logout():
    session.clear()
    return redirect(url_for("auth.login"))


def login_required(view=None):
    @functools.wraps(view)
    def wrapped(**kwargs):
        if g.user is None:
            return redirect(url_for("auth.login"))

        if view is not None:
            return view(**kwargs)

    return wrapped

todo_app/collaborator/blueprint.py
from flask import (
    Blueprint,
    abort,
    flash,
    g,
    redirect,
    render_template,
    request,
    url_for,
)
from sqlalchemy import select

from auth.models import User
from collaborator.models import Collaborator
from project.utils import get_project
from db import db
from utils import to_int
from auth.utils import login_required


bp = Blueprint(
    "collaborator", __name__, url_prefix="/collaborator", template_folder="templates"
)

bp.before_request(login_required())


@bp.get("/")
def index():
    return render_template(
        "collaborator_index.html", collaborations=g.user.collaborations
    )


@bp.route("/add", methods=("GET", "POST"))
def create():
    if request.method == "POST":
        project_id = request.form["project_id"]
        user_email = request.form["email"]
        error = None
        project = None

        if not project_id or not user_email:
            error = "Must provide a valid project id and email."

        if not error and user_email == g.user.email:
            error = "Cannot invite yourself."

        if not error:
            stmt = select(User).where(User.email == user_email)
            user = db.session.scalar(stmt)
            if user is None:
                error = f"Could not find a user for email {user_email}."

        if not error:
            project = get_project(project_id, check_collaborator=False)
            stmt = (
                select(Collaborator)
                .where(Collaborator.user_id == user.id)
                .where(Collaborator.project_id == project.id)
            )
            if db.session.scalar(stmt) is not None:
                error = "User already participating in project."

        if not error and project is not None:
            collaborator = Collaborator(user_id=user.id)
            project.collaborators.append(collaborator)
            db.session.commit()
            flash("User invited.")
            return redirect(url_for("project.show_details", project_id=project.id))

        flash(error)

    project = None
    if request.method == "GET":
        project_id = request.args["project_id"]
        project = get_project(project_id, check_collaborator=False)

    return render_template("create_collaborator.html", project=project)


@bp.get("/delete/<int:collaborator_id>")
def delete(collaborator_id):
    project_id = to_int(request.args["project_id"])
    # call to check project existence and ownership
    get_project(project_id, check_collaborator=False)

    stmt = select(Collaborator).where(Collaborator.id == collaborator_id)
    collaborator = db.session.scalar(stmt)
    if collaborator is None:
        abort(404)
    elif collaborator.project_id != project_id:
        abort(403)

    db.session.delete(collaborator)
    db.session.commit()

    return redirect(url_for("project.show_collaborators", project_id=project_id))

todo_app/templates/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %} - TODO App</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{ url_for('index') }}">TODO App</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if g.user %}
                    <a class="nav-link" href="{{ url_for('index') }}">Home</a>
                    <a class="nav-link" href="{{ url_for('collaborator.index') }}">Collaborations</a>
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    {% endif %}
                </div>
              </div>
            </div>
          </nav>

        {% set message = get_flashed_messages()[0] %}
        {% if message %}
            <div class="alert alert-warning alert-dismissible fade show">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endif %}

        <main class="container mt-5">
            {% block content %}{% endblock %}
        </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='main.js') }}"></script>
    </body>
</html>