todo_app/task/models.py
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey
from sqlalchemy.orm import relationship

from db import Base
from models import TimestampMixin


class Task(Base, TimestampMixin):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, autoincrement=True)
    project_id = Column(ForeignKey("projects.id"), nullable=False)
    text = Column(String(), nullable=False)
    completed = Column(Boolean(), nullable=False)
    added_by_id = Column(ForeignKey("users.id"), nullable=False)

    project = relationship("Project", back_populates="tasks")
    added_by = relationship("User")

todo_app/task/blueprint.py
from flask import Blueprint, flash, g, redirect, render_template, request, url_for

from db import db
from task.models import Task
from project.utils import get_project
from task.utils import get_task
from auth.utils import login_required


bp = Blueprint("task", __name__, url_prefix="/task", template_folder="templates")

bp.before_request(login_required())


@bp.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        project_id = request.form["project_id"]
        text = request.form["text"]
        completed = "completed" in request.form
        error = None

        if not project_id or not text:
            error = "Must send valid values for project ID, text, and completed."

        if not error:
            project = get_project(project_id)
            task_id = request.form.get("task_id")
            if task_id is not None:
                task = get_task(task_id)
                task.text = text
                task.completed = completed
            else:
                task = Task(text=text, completed=False, added_by_id=g.user.id)
                project.tasks.append(task)

            db.session.commit()
            flash(f"Task was {"updated" if task_id else "created"}.")
            return redirect(url_for("project.show_details", project_id=project_id))

        flash(error)

    project_id = None
    task = None
    if request.method == "GET":
        project_id = request.args["project_id"]
        # to check that project exists and ownership or collaborator
        get_project(project_id)
        task_id = request.args.get("task_id")
        if task_id is not None:
            task = get_task(task_id)

    return render_template("create_task.html", project_id=project_id, task=task)


@bp.get("/completed/<int:task_id>")
def completed(task_id):
    task = get_task(task_id)
    task.completed = not task.completed
    db.session.commit()
    return redirect(url_for("project.show_details", project_id=task.project_id))


@bp.get("/delete/<int:task_id>")
def delete(task_id):
    project_id = request.args["project_id"]
    task = get_task(task_id)
    db.session.delete(task)
    db.session.commit()
    flash("Task was deleted.")
    return redirect(url_for("project.show_details", project_id=project_id))

todo_app/templates/task/create.html
{% extends 'base.html' %}

{% if request.form.get("task_id") or task %}
    {% set update = True %}
    {% set title = "Update" %}
{% else %}
    {% set update = False %}
    {% set title = "Create" %}
{% endif %}

{% block content %}
    <h1>{% block title %}{{ title }} task{% endblock %}</h1>

    <div class="row justify-content-center">
        <form class="col-md-4" method="post">
            <input name="project_id" type="hidden" value="{{ request.form.get('project_id') or project_id }}">

            <div class="mb-3">
                <label for="text">Text</label>
                <input class="form-control" id="text" name="text" required type="text" value="{{ request.form.get('text') or task.text }}">
            </div>
            
            {% if update %}
                <input name="task_id" type="hidden" value="{{ request.form.get('task_id') or task.id }}">

                <div class="form-check mb-3">
                    <input {% if task.completed %}checked{% endif %} class="form-check-input" id="completed" name="completed" type="checkbox">
                    <label for="completed">Completed</label>
                </div>
            {% endif %}
    
            <button class="btn btn-primary">{{ title }}</button>

            {% if update %}
                <a class="btn btn-danger" href="{{ url_for('task.delete', task_id=task.id, project_id=project_id) }}">Delete</a>
            {% endif %}
        </form>
    </div>
{% endblock %}